version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
